### ISSUE TITLE
Instalation of Python bindings failed

### ISSUE THREAD

**Issue by ProkopHapala** [dftbplus/dftbplus#1264]
**Describe the bug**

I was able to compile dftb+ with `cmake -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y ..` as decribed [here](https://dftbplus-recipes.readthedocs.io/en/latest/interfaces/pyapi/pyapi.html) and [here](https://github.com/dftbplus/dftbplus/blob/main/INSTALL.rst) but it failed on `make install`

**To Reproduce**

* `cmake .. -DWITH_TBLITE=N -DWITH_SOCKETS=Y -DWITH_GPU=N -DBUILD_SHARED_LIBS=Y -DWITH_API=Y -DWITH_PYTHON=Y -DCMAKE_INSTALL_PREFIX=$HOME/SW/dftbplus`

* `make install` returns
```
...
-- Up-to-date: /home/prokop/SW/dftbplus/bin/skderivs
-- Up-to-date: /home/prokop/SW/dftbplus/bin/integvalue
-- Up-to-date: /home/prokop/SW/dftbplus/bin/polyvalue
-- Up-to-date: /home/prokop/SW/dftbplus/bin/splvalue
-- Up-to-date: /home/prokop/SW/dftbplus/bin/printunits
-- Up-to-date: /home/prokop/SW/dftbplus/bin/modes
-- Up-to-date: /home/prokop/SW/dftbplus/bin/waveplot
/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/util.py", line 212, in subst_vars
    return _subst_compat(s).format_map(lookup)
KeyError: 'DESTDIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prokop/git_SW/dftbplus/tools/dptools/setup.py", line 4, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py", line 45, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 439, in finalize_options
    self.expand_basedirs()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 619, in expand_basedirs
    self._expand_attrs(['install_base', 'install_platbase', 'root'])
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/install.py", line 613, in _expand_attrs
    val = subst_vars(val, self.config_vars)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/util.py", line 214, in subst_vars
    raise ValueError(f"invalid variable {var}")
ValueError: invalid variable 'DESTDIR'
-- Up-to-date: /home/prokop/SW/dftbplus/bin/calc_timeprop_maxpoldir
-- Up-to-date: /home/prokop/SW/dftbplus/bin/calc_timeprop_spectrum
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-targets.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-targets-relwithdebinfo.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-config.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/dftbplus-config-version.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomBlas.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/Findelsi.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/CustomLibraryFinder.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomPlumed.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomMagma.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomScalapack.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomLapack.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/cmake/dftbplus/Modules/FindCustomArpack.cmake
-- Up-to-date: /home/prokop/SW/dftbplus/lib/pkgconfig/dftbplus.pc
...
```

**Additional context**

Tested on Ubuntu 22 LTS

**Comment by vanderhe** [comment]
Hi @ProkopHapala,
I could reproduce this behavior and drafted a possible fix in #1267. Would this work for you?

Best regards
Tammo
